---
site:
  title: "Writing Your First Playbook with Ansible Lightspeed"
  url: https://demo.redhat.com/course-template
  start_page: modules::01-playbook-inventory.adoc

content:
  sources:
    - url: ./
      start_path: content
ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true
  supplemental_files: ./content/supplemental-ui

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
